Repository vmware-clarity/core, pull requests merged in 2022-03, with the labels that each got.

#2 chore: update repo urls
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/contribution-proposal.md
  README.md
  apps/website/get-started/README.md
  apps/website/get-started/developing/README.md
  docs/CODING_GUIDELINES.md
  docs/CONTRIBUTING_DESIGN.md
  docs/CONTRIBUTING_DEVELOPMENT.md
  docs/CONTRIBUTING_DOCUMENTATION.md
  docs/CONTRIBUTING_ISSUES.md
  docs/GOVERNANCE.md
  packages/angular/projects/cds-angular/package.json
  packages/core/docs/angular.stories.mdx
  packages/core/docs/angularjs.stories.mdx
  packages/core/docs/development/demo-applications.stories.mdx
  packages/core/docs/development/getting-started.stories.mdx
  packages/core/docs/development/unit-testing.stories.mdx
  packages/core/docs/preact.stories.mdx
  packages/core/docs/react.stories.mdx
  packages/core/docs/vue.stories.mdx
  packages/core/docs/welcome.stories.ts
  packages/core/npm.json
  packages/core/src/styles/themes/clr-theme.stories.mdx
  packages/eslint-plugin-clarity-adoption/package.json
  packages/react/package.json
  packages/schematics/package.json
Labels: documentation, cla-not-required

#4 fix(core:modal): fix modal and popup animations
  packages/core/src/dropdown/dropdown.stories.ts
  packages/core/src/grid/docs/row-action.story.ts
  packages/core/src/internal-components/overlay/overlay.element.spec.ts
  packages/core/src/internal-components/overlay/overlay.element.ts
  packages/core/src/internal/positioning/utils.spec.ts
  packages/core/src/internal/utils/dom.spec.ts
  packages/core/src/internal/utils/dom.ts
  packages/core/src/modal/modal.element.spec.ts
  packages/core/src/modal/modal.element.ts
  packages/core/src/modal/modal.stories.ts
Labels: bug, cla-not-required

#3 chore: update repo urls
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/contribution-proposal.md
  README.md
  apps/website/get-started/README.md
  apps/website/get-started/developing/README.md
  docs/CODING_GUIDELINES.md
  docs/CONTRIBUTING_DESIGN.md
  docs/CONTRIBUTING_DEVELOPMENT.md
  docs/CONTRIBUTING_DOCUMENTATION.md
  docs/CONTRIBUTING_ISSUES.md
  docs/GOVERNANCE.md
  packages/angular/projects/cds-angular/package.json
  packages/core/docs/angular.stories.mdx
  packages/core/docs/angularjs.stories.mdx
  packages/core/docs/development/demo-applications.stories.mdx
  packages/core/docs/development/getting-started.stories.mdx
  packages/core/docs/development/unit-testing.stories.mdx
  packages/core/docs/preact.stories.mdx
  packages/core/docs/react.stories.mdx
  packages/core/docs/vue.stories.mdx
  packages/core/docs/welcome.stories.ts
  packages/core/npm.json
  packages/eslint-plugin-clarity-adoption/package.json
  packages/react/package.json
  packages/schematics/package.json
Labels: cla-not-required

#6 chore: github build action (main)
  .github/workflows/build.yml
Labels: cla-not-required

#5 chore: github build action (beta)
  .github/workflows/build.yml
Labels: cla-not-required

#8 feat(core:icon): adding badges/alerts for namespace icon
  packages/core/src/icon/shapes/namespace.ts
Labels: cla-not-required

#15 feat(core:icon): adding contract icon
  packages/core/src/icon/collections/social.ts
  packages/core/src/icon/icon.performance.ts
  packages/core/src/icon/index.ts
  packages/core/src/icon/shapes/contract.ts
Labels: enhancement, cla-not-required

#18 fix(core:icon): export digital signature icon
  packages/core/src/icon/index.ts
Labels: cla-not-required
