Repository vmware-clarity/core, pull requests merged in 2022-07, with the labels that each got.

#117 chore: use single non-headless browser when watching angular tests
  projects/angular/karma.conf.js
Labels: cla-not-required, type:chore

#119 feat: update homepage in package manifests
  projects/adoption/package.lib.json
  projects/angular/projects/cds-angular/package.json
  projects/core/package.lib.json
  projects/react/package.lib.json
Labels: cla-not-required, type:feat

#120 feat: update homepage in package manifests (backport)
  projects/adoption/package.lib.json
  projects/angular/projects/cds-angular/package.json
  projects/core/package.lib.json
  projects/react/package.lib.json
Labels: cla-not-required, type:feat, backport

#123 fix(modal): react - fix modal visibility when hidden="false"
  .gitignore
  projects/core/src/internal-components/overlay/overlay.element.scss
  projects/core/src/internal/base/base.element.scss
Labels: cla-not-required
