Repository vmware-clarity/core, pull requests merged in 2022-06, with the labels that each got.

#98 fix(navigation): move navigation component back to beta
  projects/core/src/navigation/navigation-group.element.ts
  projects/core/src/navigation/navigation-item.element.ts
  projects/core/src/navigation/navigation.element.ts
  projects/core/src/navigation/navigation.stories.mdx
Labels: cla-not-required

#93 chore: send analytics pageviews for storybook
  projects/core/.storybook/manager-head.html
Labels: cla-not-required, type:chore

#91 fix(pagination): fix disabled css and remove full width
  projects/core/src/pagination/pagination.element.scss
  projects/core/src/pagination/pagination.stories.ts
Labels: cla-not-required

#96 fix(button): revert disabled button color to v5 behavior
  projects/core/src/button/button.element.scss
Labels: cla-not-required

#102 chore: deploy storybook with no alias for main branch
  .github/workflows/release.yml
Labels: type:chore

#105 fix(spacing): use base 20 fallback spacing logic
  projects/core/.storybook/preview.js
  projects/core/build/build.tokens.ts
  projects/core/src/index.performance.ts
Labels: cla-not-required

#104 chore: record virtual page data for storybook analytics
  projects/core/.storybook/manager-head.html
Labels: cla-not-required, type:chore

#108 fix(modal): fix react modal-header-actions export
  projects/core/custom-elements.json
  projects/core/src/modal/modal-header-actions.element.ts
  projects/core/src/modal/modal.stories.mdx
  projects/core/src/modal/modal.stories.ts
  projects/react/src/modal/index.tsx
Labels: cla-not-required

#109 fix(alert): fix alert close button positioning
  projects/core/custom-elements.json
  projects/core/src/alert/alert-group.stories.ts
  projects/core/src/alert/alert.element.scss
  projects/core/src/alert/alert.element.ts
  projects/core/src/button-action/button-action.element.spec.ts
  projects/core/src/button-action/button-action.element.ts
Labels: cla-not-required
