Repository vmware-clarity/core, pull requests merged in 2022-04, with the labels that each got.

#33 (port) feat(core:icon): adding contract icon
  projects/core/custom-elements.json
  projects/core/src/icon/collections/social.ts
  projects/core/src/icon/icon.performance.ts
  projects/core/src/icon/index.ts
  projects/core/src/icon/shapes/contract.ts
Labels: cla-not-required

#20 fix: hidden attr
  projects/core/custom-elements.json
  projects/core/src/internal-components/overlay/overlay.element.spec.ts
  projects/core/src/internal-components/overlay/overlay.element.ts
  projects/core/src/internal/positioning/utils.spec.ts
  projects/core/src/modal/modal.stories.ts
Labels: cla-not-required, type:fix

#34 fix(radio-group): allow custom input name
  projects/core/src/radio/radio-group.element.spec.ts
  projects/core/src/radio/radio-group.element.ts
Labels: cla-not-required

#37 fix(radio-group): allow custom input name (beta)
  projects/core/src/radio/radio-group.element.spec.ts
  projects/core/src/radio/radio-group.element.ts
Labels: cla-not-required

#36 fix(react:selection-panel): wrap cds-radio-panel instead of cds-radio (beta)
  projects/react/src/selection-panels/radio/__snapshots__/index.test.tsx.snap
  projects/react/src/selection-panels/radio/index.test.tsx
  projects/react/src/selection-panels/radio/index.tsx
Labels: cla-not-required

#35 fix(react:selection-panel): wrap cds-radio-panel instead of cds-radio
  projects/react/src/selection-panels/radio/__snapshots__/index.test.tsx.snap
  projects/react/src/selection-panels/radio/index.tsx
Labels: cla-not-required

#39 chore: run core library build as part of public-api:update script (beta)
  projects/core/package.json
Labels: type:chore, backport

#38 chore: run core library build as part of public-api:update script
  projects/core/package.json
Labels: cla-not-required, type:chore

#41 fix(icon): export launchpad icon
  projects/core/custom-elements.json
  projects/core/src/icon/index.ts
Labels: cla-not-required

#47 fix(radio-group): treat cds-radio-panel like cds-radio
  projects/core/src/radio/radio-group.element.spec.ts
  projects/core/src/radio/radio-group.element.ts
Labels: cla-not-required

#46 fix(radio-group): treat cds-radio-panel like cds-radio
  projects/core/src/radio/radio-group.element.spec.ts
  projects/core/src/radio/radio-group.element.ts
Labels: cla-not-required, backport

#53 chore: fix ci demo path
  .github/workflows/build.yml
  .github/workflows/demo.yml
Labels: cla-not-required
